version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
    restart: unless-stopped
    command: npm run dev

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docket_calendar
      - MYSQL_USER=docket_user
      - MYSQL_PASSWORD=docket_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/01-init.sql
    restart: unless-stopped

volumes:
  mysql-data: 